### ISSUE TITLE
API-метод создания бронирования

### ISSUE THREAD

**Issue by ALEXXXANDRO** [Gorbokonenko-Dikovitskiy-Kolegov/Itmo.Dormitory-back#3]
- Валидация реквеста согласно ограничениям в домене
- В респонсе отдаем Id,  Фамилия + инициалы хозяина,  дату-время брони и имя комнаты

**Comment by snowywhitee** [comment]
Чтоб был хозяин надо иметь аккаунты. В ветке только создание слота
