### ISSUE TITLE
API-метод редактирования бронирования

### ISSUE THREAD

**Issue by ALEXXXANDRO** [Gorbokonenko-Dikovitskiy-Kolegov/Itmo.Dormitory-back#5]
- Валидация согласно ограничениям домена
- В респонсе отдаем Id,  Фамилия + инициалы хозяина,  дату-время, название комнаты

**Comment by snowywhitee** [comment]
Аккаунты будут добавиЦа. Технически уже реализовано - за бронь отвечает бит Reserved
