### ISSUE TITLE
API-метод получения всех бронирований резидента

### ISSUE THREAD

**Issue by ALEXXXANDRO** [Gorbokonenko-Dikovitskiy-Kolegov/Itmo.Dormitory-back#7]
Возвращает респонс со списком бронирований:
- ID брони
- Дата-время
- Название комнаты

**Comment by snowywhitee** [comment]
Нет аккаунтов - нет списка :р В ветке возвращение списка бронирований на комнату (отображается при просмотре доступных слотов)
